apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-monolitic.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app-monolitic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "app-monolitic.selectorLabels" . | nindent 4 }}

